### ISSUE TITLE
How would I programmatically throw out a card?

### ISSUE THREAD

**Issue by HEATH3N** [goweiwen/vue-swing#1]

**Comment by goweiwen** [comment]
The `VueSwing` component exposes the `stack` and `card` variables, which you can use like so:
```vue
<vue-swing ref="wrapper">
   <div>Card 1</div>
   <div>Card 2</div>
   <div>Card 3</div>
</vue-swing>
```
```js
this.$refs.wrapper.cards[0].throwOut(x, y);
```

**Comment by HEATH3N** [comment]
Hmm; it doesn't seem to be working for me. `this.$refs.wrapper.cards` contains the same number of elements before and after I call `throwOut` and there's no visible change.

**Comment by goweiwen** [comment]
Yes, that's how it should be. In Swing, throwing a card out is different from destroying a card. When you throw a card out, you emit a `throwout` event and send the card aside, while the DOM element still exists.

If you wish to remove the item instead, call `card.destroy()` or remove the element directly.
