### ISSUE TITLE
Best way to change the threshold on how far a card needs to be dragged before having the throw methods called?

### ISSUE THREAD

**Issue by danstans** [goweiwen/vue-swing#10]
My cards are roughly 90% of the view width and getting them to swipe and disappear is kinda of tricky. Is there any way to reduce the amount of distance needed to swipe to have the functions called?

**Comment by goweiwen** [comment]
You can override the `throwOutConfidence` to return 1 if the card should be thrown out. The function signature can be found [here](https://github.com/gajus/swing/blob/c7cebdf9e3fddb51509b645b6803760f86b3c930/src/Card.js#L488).

**Comment by danstans** [comment]
Hmm thank you, I tried to add the throwOutConfidence to my config in my data. 
```
  data () {
    return {
      config: {
        allowedDirections: [VueSwing.Direction.LEFT, VueSwing.Direction.RIGHT],
        throwOutConfidence: 1
      }
    }
  },
```

However, this doesn't seem to be making the change I need. Should I change it to a function which returns 1?

**Comment by danstans** [comment]
Just realized I was writing my function wrong the whole time! It works now, thank you very much. For future reference I was able to change it to this:
```
  data () {
    return {
      config: {
        allowedDirections: [VueSwing.Direction.LEFT, VueSwing.Direction.RIGHT],
        throwOutConfidence: function () {
          return 1
        }
      }
    }
  },
```
As a follow up question for future reference, what would be the difference of changing it to a number between 0 and 1, such as 0.8? It seems to not work very well on non-1 values.

**Comment by goweiwen** [comment]
My mistake, you should implement `isThrowOut` instead. It should be a function that takes in a `throwOutConfidence` from 0 to 1 and returns a Boolean representing whether to throw the card out or not. The default implementation returns true when `throwOutConfidence` is 1. You can try something like `throwOutConfidence => throwOutConfidence > 0.5`, for example, to throw the card out when it's dragged halfway.

**Comment by danstans** [comment]
Okay, for the record this is the code I have implemented now.
```
  data () {
    return {
      config: {
        allowedDirections: [VueSwing.Direction.LEFT, VueSwing.Direction.RIGHT],
        isThrowOut: function (throwOutConfidence) {
          console.log(throwOutConfidence)
          return throwOutConfidence > 0.5
        }
      }
    }
  },
```
It seems that the throwOutConfidence numbers range from -200 to 200 instead of values between 0 and 1. I could normalize this value but I am just checking to see if this appears correct. Thank you for all your help!!

**Comment by goweiwen** [comment]
Oops, I haven't used this in a while. The parameters `isThrowOut` should take in are `(xOffset, yOffset, element, throwOutConfidence)`, so the -200 to 200 is actually the `xOffset`. You can ignore the first 3 parameters and only look at `throwOutConfidence`, which should be between 0 and 1.

**Comment by danstans** [comment]
Here's the solution for the future people:
```
  data () {
    return {
      config: {
        allowedDirections: [VueSwing.Direction.LEFT, VueSwing.Direction.RIGHT],
        isThrowOut: function (xOffset, yOffset, element, throwOutConfidence) {
          return throwOutConfidence > 0.5
        }
      }
    }
  },
```
Closing for now, thank you for all of the help! nice library!!

**Comment by jancborchardt** [comment]
Thank you so much @danstans @goweiwen! Will use this in the [Keep or Sweep](http://keeporsweep.net/) app we are working on. :+1:
