### ISSUE TITLE
Normal set up from docs is throwing error "throwin": got undefined

### ISSUE THREAD

**Issue by Dnguye92** [goweiwen/vue-swing#13]
Just trying to test this package on my Vue app exactly like how it's shown in the readme but I'm getting console errors showing that the events "throwin" and "throwout" are undefined?

```
<template>
    <VueSwing
      @throwout="throwout"
      @throwin="throwin"
       :config="config"
    >
      <div class="box">Throw me!</div>
    </VueSwing>
</template>
<script>
import VueSwing from 'vue-swing';
Vue.component('vue-swing', VueSwing);
export default {
    components: {
        VueSwing
     }
}
</script>
```

**Comment by goweiwen** [comment]
The `throwin` and `throwout` events are optional and are emitted when Swing (the underlying library) emits them. If you need it, you can use it like this:

```vue
<template>
    <VueSwing
      @throwout="throwout"
      @throwin="throwin"
      :config="config"
    >
        <div class="box">Throw me!</div>
    </VueSwing>
</template>
<script>
import VueSwing from 'vue-swing';

export default {
    components: {
        VueSwing
    },
    methods: {
        throwin() {
            console.log("throwing in!");
        },
        throwout() {
            console.log("throwing out!");
        }
    }
}
</script>
```

The `examples` directory has an example app that you can learn from.

Note: you don't need to call `Vue.component('vue-swing', VueSwing)` unless you want the component to be available globally.
