### ISSUE TITLE
How to add a card by script?

### ISSUE THREAD

**Issue by magusfabius** [goweiwen/vue-swing#3]
I created a Vue component called 'SpecialCard' and I would like to dynamically add an instance of 'SpecialCard' filled with some data that I retrive from a server (an image url and a description) to the vue-swing stack. 

As the official documentation suggests I tried to push a new card in this way:
 `this.$refs.swinger.stack.createCard(newCard.$el)`

Where newCard is an instance of the 'SpecialCard' component.
THe result is that it only works the first time and if I try to add again a new instance to the stack the browser crashes. Moreover the cards have a strange behavior. When they are thrown out they get stuck without disappearing.

What am I doing wrong?
Is that a good way to add cards by script to the vue-swing component?

I replicated this issue on [codesandbox](https://codesandbox.io/s/1851ynl1v3?module=%2Fcomponents%2FHello.vue)

P.S. I would like to provide some examples of the use of vue-swing. I tried to search on the web but I didn't find nothing, so here I am ;)

**Comment by goweiwen** [comment]
Using `stack.createCard()` isn't recommended. Instead, simply adding a node to the `vue-swing` component will create a new card.

This library simply wraps Swing, which does not destroy a card after it gets thrown out. You have to write your own functions to do that.

I have added an [example](https://github.com/goweiwen/vue-swing/blob/master/examples/src/App.vue) in the repository. 

Take a look and let me know if you still face any issues.

**Comment by magusfabius** [comment]
Great! Thank you so much! I created an [example](https://codesandbox.io/s/r0rqlk81p?module=%2Fcomponents%2FHello.vue) in which you push a card-component fed with an image and a name retrived from web api. 

I understand that the element inside vue-swing must have the css proprety  `position: absolute;` otherwise the elements inside vue-swing will be displayed in different positions.

Thank you again!

**Comment by HEATH3N** [comment]
At least for me, the example you provided only works to throw out a single card; the rest of the cards in the stack are removed without animation. Adding a new card lets that card be thrown out, but then the remainder stop working again.

**Comment by goweiwen** [comment]
I introduced a regression in the previous update. Thanks for spotting it, @HEATH3N. I've pushed a fix up now. In the future, please create a new issue.
