### ISSUE TITLE
Dependency was not found

### ISSUE THREAD

**Issue by PickleNik** [goweiwen/vue-swing#4]
I'm using Vue-cli, so I installed vue-swing with npm and imported it to main.js file. Then I put your example in my template. When I try to run terminal says the folllowing: 

```
 ERROR  Failed to compile with 1 errors                                 14:24:28

This dependency was not found:

* swing in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-swing/VueSwing.vue
```
It also says that I can install swing with `npm install --save swing`, but then all of properties or events in vue-swing component are not working. :disappointed:

**Comment by goweiwen** [comment]
Did you install `swing` as well (using `npm install --save swing`)?

**Comment by PickleNik** [comment]
First I installed `vue-swing` with `npm install --save vue-swing`,
then, after getting and error, I installed `swing` with `npm install --save swing`.

**Comment by goweiwen** [comment]
Did you try restarting the server? It seems like `swing` cannot be found, which should not be the case. Can you check that `swing` is in the `dependencies` section of your `package.json`?

**Comment by PickleNik** [comment]
After installing only `vue-swing`, the `swing` is not there.
![screenshot from 2018-02-17 15-12-44](https://user-images.githubusercontent.com/31113245/36345245-16933092-13f5-11e8-93a8-d3705b5ca37f.png)

**Comment by goweiwen** [comment]
Yes, that is supposed to be the case because `swing` is a peer-dependency of `vue-swing`, meaning it needs to be installed separately. Try running `npm install --save swing` as well and restart the server.

**Comment by PickleNik** [comment]
Ok, it works, but I didn't see it in installing directions. Thanks!

**Comment by goweiwen** [comment]
That's a good point, I'll remember to add it in next time.

**Comment by TheFrogDaddy** [comment]
Guys I still get this. I have both dependancies, any ideas?

<img width="341" alt="screenshot 2018-12-19 at 23 00 50" src="https://user-images.githubusercontent.com/5995357/50253417-0a313500-03e2-11e9-9582-01e7c043f6f1.png">
<img width="533" alt="screenshot 2018-12-19 at 23 02 09" src="https://user-images.githubusercontent.com/5995357/50253455-292fc700-03e2-11e9-9e28-4c991f55c5d5.png">

![image](https://user-images.githubusercontent.com/5995357/50253526-5ed4b000-03e2-11e9-8dc0-9f76dc00240a.png)

i'm using vue-cli 3
